name: Isort
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort

    - name: Analyse the code with isort
      run: isort --check .